<?php
// $Id$

/**
 * @file
 * Creates a list of URLs for search engines to index.
 *
 * @version $Id$
 * @author David Kent Norman <deekayen {{at}} deekayen [[dot]] net>
 * @link http://deekayen.net/
 */

/**
 * Implementation of hook_help().
 */
function urllist_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      return t('Creates a list of URLs at q=urllist.txt or urllist.txt');
   case 'admin/settings/urllist':
      return t('The following options allow you to alter the behavior of the URLlist module.');
  }
}

/**
 * Implementation of hook_menu().
 */
function urllist_menu($may_cache) {
  $items = array();

  $items[] = array('path' => 'urllist.txt', 'access' => true,
    'callback' => 'urllist_output', 'type' => MENU_CALLBACK, 'title' => 'urllist.txt');
  $items[] = array('path' => 'urllist', 'access' => true,
    'callback' => 'urllist_output', 'type' => MENU_CALLBACK, 'title' => 'urllist');

  return $items;
}

/**
 * Implementation of hook_settings().
 *
 * @return array
 */
function urllist_settings() {
  $form['urllist_logacc'] = array(
    '#type'          => 'checkbox',
    '#title'         => 'Log accesses',
    '#default_value' => variable_get('urllist_logacc', 0),
    '#description'   => t('If enabled, a watchdog entry will be made each time the URL list is accessed, containing information about the requestor.')
  );
  return $form;
}

/**
 * Print list of URLs in plaintext format
 *
 */
function urllist_output() {
  if(!ini_get('safe_mode')) {
    set_time_limit(240);
  }
  header('Content-type: text/plain');
  print url('', NULL, NULL, TRUE) . "\n";
  $result = db_query("SELECT n.nid, n.type, n.status, n.promote, n.changed, u.dst FROM {node} n LEFT JOIN {url_alias} u ON u.src=CONCAT('node/',n.nid)");
  while($node = db_fetch_object($result)) {
    if($node->status) { // add check for if the node type is disabled or not
      if(isset($node->dst)) { // alias is named
        print url($node->dst, NULL, NULL, TRUE) . "\n";
      }
      else {
        print url('node/' . $node->nid, NULL, NULL, TRUE) . "\n";
      }
    }
  }
  if(module_exist('taxonomy')) {
    $result = db_query("SELECT d.tid FROM {term_data} d");
    while($topic = db_fetch_object($result)) {
      print url('taxonomy/term/' . $topic->tid, NULL, NULL, TRUE) . "\n";
    }
  }
  if(module_exist('image')) {
    print url('image', NULL, NULL, TRUE) . "\n";
  }
  if(module_exist('randomizer')) {
    print url('randomizer', NULL, NULL, TRUE) . "\n";
  }
  if(module_exist('blog')) {
    print url('blog', NULL, NULL, TRUE) . "\n";
  }
  if(variable_get('urllist_logacc',0)) {
    watchdog('urllist','URL list downloaded by ' . getenv('HTTP_USER_AGENT') . ' at ' . getenv('REMOTE_ADDR') . '.');
  }
}

?>
