<?php
// $Id$

/**
 * @file
 * Creates a list of URLs for search engines to index.
 *
 * @version $Id$
 * @author David Kent Norman <deekayen {{at}} deekayen [[dot]] net>
 */

/**
 * Implementation of hook_help().
 */
function urllist_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      return t('Creates a list of URLs at q=urllist');
   case 'admin/settings/gsitemap':
      return t('The following options allow you to alter the behavior of the URLlist module.');
  }
}

/**
 * Implementation of hook_menu().
 */
function urllist_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array('path' => 'urllist', 'title' => t('urllist'),
      'callback' => 'urllist_output',
      'type' => MENU_CALLBACK,
      'access' => 1);
  }

  return $items;
}

/**
 * Implementation of hook_settings().
 *
 * @return array
 */
function urllist_settings() {
  $form['urllist_logacc'] = array(
    '#type'          => 'checkbox',
    '#title'         => 'Log accesses',
    '#default_value' => variable_get('urllist_logacc', 0),
    '#description'   => t('If enabled, a watchdog entry will be made each time the URL list is accessed, containing information about the requestor.')
  );
  return $form;
}

/**
 * Print list of URLs in plaintext format
 *
 */
function urllist_output() {
  header("Content-type: text/plain");
  print url('', NULL, NULL, TRUE) . "\n";
  $result = db_query(db_rewrite_sql("SELECT nid, {node}.type, {node}.status, {node}.promote, {node}.changed, {url_alias}.dst FROM {node} LEFT JOIN {url_alias} ON {url_alias}.src=CONCAT('node/',{node}.nid)",'node'));
  while($node = db_fetch_object($result)) {
    if($node->status) { // add check for if the node type is disabled or not
      if(isset($node->dst)) { // alias is named
        print url($node->dst, NULL, NULL, TRUE) . "\n";
      }
      else {
        print url('node/' . $node->nid, NULL, NULL, TRUE) . "\n";
      }
    }
  }
  if(variable_get('urllist_logacc',0)) {
    watchdog('urllist','URL list downloaded by ' . getenv('HTTP_USER_AGENT') . ' at ' . getenv('REMOTE_ADDR') . '.');
  }
}

?>
